      
spring:
    profiles:
      active: dev
      
     
    datasource:          url: jdbc:h2:mem:test1      driver-class-name: org.h2.Driver
    jpa:      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:        ddl-auto: update  

    h2:      console:        enabled: true
            application:      name: EmployeeTrainingService      sleuth:      sampler:        probability: 1.0
        
    zipkin:      base-url: http://localhost:9411/
     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka   instance:    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

        
management:
  endpoints:
    web:
      exposure:
        include: "*"     
   
 
server:
  servlet:
    context-path: /employeetraining
  port: 8080
    error:    whitelabel:      enabled: false

---

spring:      
  profiles: dev
server:  port: 8081
  
---

spring:  profiles: test
  
server:  port: 8082